---
title: "R Project"
output: html_document
date: "2022-11-25"
author: 'Daniel Setiawan'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(tidyr)
library(ggplot2)
library(lubridate)
library(ggthemes)
library(tidyverse)
```

*Data* <http://insideairbnb.com/get-the-data> column name dictionary: <https://docs.google.com/spreadsheets/d/1b_dvmyhb_kAJhUmv81rAxl4KcXn0Pymz>

```{r}
# detect all files
files.listings = list.files(path = './listings', pattern = '*.csv', full.names = TRUE)
files.reviews = list.files(path = './reviews', pattern = '*.csv', full.names = TRUE)
```

```{r}
# add city and state columns to all dataframes
# cities = gsub('\\./|\\.csv|listings|/', '', files.listings)
# names(cities) = c('NC', 'TX', 'MA', 'FL', 'MA', 'IL', 'NV', 'OH', 'TX',
#                 'CO', 'TX', 'HI', 'NJ', 'CA', 'CA', 'TN', 'AK', 'NJ',
#                 'NY', 'CA', 'CA', 'OR', 'RI', 'MA', 'CA', 'CA', 'CA',
#                 'CA', 'CA', 'WA', 'MN', 'DC')
# 
# for (file in files.listings) {
#   city_ = gsub('\\./|\\.csv|listings|/|2', '', file)
#   state_ = unique(names(cities)[cities == city_])
#   df = read_csv(file, show_col_types = FALSE)
#   df %>%
#     mutate(city = city_,
#            state = state_) %>%
#     write_csv(file)
# }
```

```{r}
# combine all cities into one dataframe
# due to null values, its easier to convert all columns as type c
raw_listings.df = files.listings %>%
  lapply(read_csv, col_types = cols(.default = 'c')) %>%
  bind_rows

# lets also combine all the different reviews
raw_reviews.df = files.reviews %>%
  lapply(read_csv, col_types = cols(.default = 'c')) %>%
  bind_rows

raw_listings.df
raw_reviews.df
```

```{r}
raw_listings.df %>%
  mutate(id = parse_date_time(host_since, c('ymd', 'dmy', 'mdy')),
         listing_url = year(id))
```

*Cleaning up the data*

#listings.df
```{r}
# removing columns we don't need
listings.df = raw_listings.df %>%
  select(-c(2:5, 9, 11, 20:23, 31:32, 44:47, 50, 52:54, 56, 58:59, 69, 71:74))

#removing na from selected columns
listings.df = listings.df %>%
  drop_na(c(description, host_since, bedrooms, beds, bathrooms_text))

#making df readable and easy to analyze
listings.df = listings.df %>%
  mutate(across(c(price, host_acceptance_rate, host_response_rate, 
                  host_response_time), ~ gsub(',|\\$|%|N/A', '', .)),
         bathrooms = ifelse(grepl('half-bath', bathrooms_text), 
                            0.5, gsub('[^0-9.]', '',bathrooms_text)),
         across(c(review_scores_rating, review_scores_accuracy, 
              review_scores_cleanliness, review_scores_checkin, 
              review_scores_communication, review_scores_location,
              review_scores_value, reviews_per_month, accommodates,
              bedrooms, beds, minimum_nights, maximum_nights, 
              minimum_nights_avg_ntm, maximum_nights_avg_ntm, price,
              number_of_reviews, host_total_listings_count, bathrooms,
              price, host_acceptance_rate, host_response_rate,
              availability_365), as.numeric),
         across(c(description, host_about), ~ str_count(., '\\s+') + 1),
         across(c(host_since, last_review), ~ 
                  parse_date_time(., c('ymd', 'dmy', 'mdy'))),
         title_len = str_length(name),
         num_hosts = str_count(host_name, 'and|And|\\&') + 1,
         amenities_count = str_count(amenities, '"') / 2,
         num_verification = str_count(host_verifications, "'") / 2,
         bathrooms_text = ifelse(grepl('hared', bathrooms_text), 
                                 'shared', 'private'),
         across(c(host_response_time, bathrooms_text, property_type,
                  room_type), factor),
         across(c(instant_bookable, host_has_profile_pic, 
                  host_identity_verified, host_is_superhost), as.logical))

# removing additional null values
listings.df = listings.df %>%
  filter(!price == 0)

# and outliers
var_ = listings.df$price

quartiles = quantile(var_, probs=c(0.25, 0.75))
iqr = IQR(var_)

lower = quartiles[1] - 1.5 * iqr
upper = quartiles[2] + 1.5 * iqr

listings.df = subset(listings.df, var_ > lower & var_ < upper)
```

#reviews.df
```{r}

# making date as_date format
# also adding additional columns: month, year, quarter
reviews.df = raw_reviews.df %>%
  group_by(date) %>%
  mutate(date = ymd(date),
         month = month(date),
         year = year(date),
         quarter = case_when(month %in% c(1:3) ~ 'Q1',
                             month %in% c(4:6) ~ 'Q2', 
                             month %in% c(7:9) ~ 'Q3',
                             month %in% c(10:12) ~ 'Q4'))

# merging price with columns and roomtype
reviews.df = raw_listings.df %>%
  select(id, price, room_type, accommodates, bathrooms, bedrooms, beds, host_since) %>%
  mutate(price = as.integer(gsub(',|\\$|%|N/A', '', price))) %>%
  merge(., reviews.df, by.x = 'id',
        by.y = 'listing_id') %>%
  distinct()
```

```{r}
accommodates, bathrooms, bedrooms, beds, host_since
```


```{r}
listings.df
reviews.df
```
*Analysis*

```{r}
airbnb_red = 'FC642D'
airbnb_green = '00A699'
```


```{r}
listings.df %>%
  ggplot(aes(price, reorder(state, price))) +
  geom_boxplot(aes(fill = airbnb_red), show.legend = FALSE) +
  theme_few() +
  scale_x_continuous(breaks = c(100, 200, 300),
                     labels = c('$100', '$200', '$300'),
                     limits = c(0, 400)) +
  labs(title = 'Average Cost by State',
       x = 'Price per night (USD)',
       y = 'State', 
       color = FALSE)
  ggsave('Cost by State - Boxplot.png', width = 10, height = 6)
```

```{r pressure, echo=FALSE}
listings.df %>%
  group_by(state) %>%
  summarise(price = mean(price)) %>%
  ggplot(aes(price, reorder(state, price))) +
  geom_col(aes(fill = airbnb_red), show.legend = FALSE) +
  theme_few() +
  scale_x_continuous(breaks = c(0, 100, 200),
                     labels = c(0, '$100', '$200'),
                     limits = c(0, 300)) +
  labs(title = 'Average Cost by State',
       x = 'Price per night (USD)',
       y = 'State')
  ggsave('Cost by State - Barplot.png', width = 10, height = 6)
```

```{r}
listings.df %>%
  filter(number_of_reviews < 2000) %>%
  ggplot(aes(price, number_of_reviews)) +
  geom_col(aes(color = airbnb_red), show.legend = FALSE) +
  facet_wrap(. ~ room_type, scales = 'free') +
  theme_few() +
  scale_x_continuous(breaks = c(0, 200, 400),
                     labels = c(0, '$200', '$400'),
                     limits = c(0, 400)) +
  labs(title = 'Room Cost vs. Reviews',
       color = 'Room Type',
       x = 'Price per night (USD)',
       y = 'Number of Reviews')
  ggsave('Room Cost by Reviews.png', width = 10, height = 6)
```


```{r}
listings.df %>%
  filter(!number_of_reviews > 2000) %>%
  ggplot(aes(price, number_of_reviews)) +
  geom_point(aes(color = airbnb_red), show.legend = FALSE) +
  theme_few() +
  labs(title = 'Distribution of Price and Reviews',
       x = 'Price (USD)',
       y = 'Number of Reviews') +
  scale_x_continuous(breaks = c(0, 250, 500), labels = c('0', '$250', '$500')) +
  scale_y_continuous(breaks = c(0, 500, 1e3, 1.5e3, 2e3), 
                     labels = c('0', '0.5K', '1K', '1.5K', '2K'))
  ggsave('Distribution of Reviews - Scatter.png', width = 10, height = 6)
```


```{r}
listings.df %>%
  group_by(city) %>%
  summarise(count = sum(number_of_reviews)) %>%
  arrange(desc(count)) %>%
  ggplot(aes(count, reorder(city, count))) +
  geom_col(aes(fill = airbnb_red), show.legend = FALSE) + 
  theme_few() +
  labs(title = 'Review Count by City',
       x = 'Number of Reviews',
       y = 'City') +
  scale_x_continuous(breaks = c(0, 5e5, 1e6), labels = c('0', '500K', '1M'))
  ggsave('Reviews by City - Barplot.png', width = 10, height = 6)
```

```{r}
amenities.df = listings.df %>%
  mutate(amenities = tolower(gsub('\\]|\\[|"', '', amenities))) %>%
  tidyr::separate_rows(amenities, sep = ', ') %>%
  mutate(amenities = case_when(grepl('coffee', amenities) ~ 'coffee', 
                               grepl('long term', amenities) ~ 'long-term stay',
                               grepl('parking|garage|carport', amenities) ~ 'parking',
                               grepl('shampoo|condition|essential|soap', amenities) ~ 'toiletries',
                               grepl('tv|netflix|hulu|streaming|cable|roku|hbo|prime video|dvd', amenities) ~ 'tv / streaming',
                               grepl('washer|dryer|laundry', amenities) ~ 'laundry',
                               grepl('patio|balcony', amenities) ~ 'outdoor space',
                               grepl('hot tub|pool|jacuzzi|sauna', amenities) ~ 'outdoor tub',
                               grepl('staff', amenities) ~ 'concierge',
                               grepl('ev', amenities) ~ 'ev charging',
                               grepl('gym', amenities) ~ 'gym',
                               grepl('wifi', amenities) ~ 'wifi',
                               grepl('ac|a/c', amenities) ~ 'a/c',
                               grepl('heat', amenities) ~ 'heater',
                               grepl('sound|music|stereo|bluetooth|aux', amenities) ~ 'music',
                               grepl('game|ping pong|billiard', amenities) ~ 'gameroom',
                               grepl('fridge|refrigerator|freezer|toaster', amenities) ~ 'kitchen',
                               grepl('oven|dishes|cooking|microwave|stove', amenities) ~ 'kitchen',
                               grepl('camera', amenities) ~ 'security camera',
                               grepl('alarm|fire|smoke|extinguisher|first aid', amenities) ~ 'safety',
                               grepl('pillows|blankets|linens', amenities) ~ 'linens',
                               TRUE ~ amenities)) %>%
  distinct()
```


```{r}
amenities.df %>%
  group_by(amenities) %>%
  summarise(count = n()) %>%
  arrange(desc(count))
```


```{r}
amenities.df %>%
  group_by(amenities) %>%
  summarise(count = n()) %>%
  arrange(desc(count)) %>%
  head(25) %>%
  ggplot(aes(count, reorder(amenities, count))) + 
    geom_col(aes(fill = airbnb_red), show.legend = FALSE) +
    theme_few() +
    labs(title = 'Amenities Offered by Hosts',
       x = 'Count',
       y = 'Amenities') +
    scale_x_continuous(breaks = c(0, 7.5e4, 1.5e5, 2.25e5), labels = c('0', '75K', '150K', '225K'))
  ggsave('Amenities Offered by Hosts - Barplot.png', width = 10, height = 6)
```





```{r}
listings.df %>%
  filter(grepl('ishwasher', amenities))
```


```{r}
listings.df %>%
  na.omit(host_is_superhost) %>%
  ggplot(aes(city, number_of_reviews)) +
  geom_point(aes(color = host_is_superhost)) +
  facet_grid(. ~ host_is_superhost) +
  theme_few()
  
```
```{r}
listings.df %>%
  group_by(room_type) %>%
  summarise(count = n()) %>%
  arrange(desc(count)) %>%
  head(10) %>%
  ggplot(aes(count, reorder(room_type, count))) +
  geom_col(aes(fill = airbnb_red), show.legend = FALSE) +
  theme_few() +
  labs(title = 'Popularity by Property',
     x = 'Count',
     y = 'Room Type') 
  # scale_x_continuous(breaks = c(0, 2.5e4, 5e4), labels = c('0', '25K', '50K'))
# ggsave('Popularity by Property - Barplot.png', width = 10, height = 6)
```

```{r}
listings.df %>%
  ggplot(aes(price)) +
  geom_density(aes(fill = airbnb_red), show.legend = FALSE) +
  scale_x_continuous(breaks = c(0, 250, 500)) +
  facet_grid(. ~ room_type, scales = 'free') +
  theme_few() +
  labs(title = 'Price Distribution by Property', 
       x = 'Price (USD)', 
       y = 'Density')
ggsave('Price Property Distribution - Density.png', width = 10, height = 6)
```


```{r}
listings.df %>%
  mutate(property_type = gsub('shared |room |in |private |entire ', '', tolower(property_type))) %>%
  group_by(property_type) %>%
  summarise(count = n()) %>%
  arrange(desc(count)) %>%
  head(10) %>%
  ggplot(aes(count, reorder(property_type, count))) +
  geom_col(aes(fill = airbnb_red), show.legend = FALSE) +
  theme_few() +
  labs(title = 'Popularity by Property',
   x = 'Count',
   y = 'Room Type') +
  scale_x_continuous(breaks = c(0, 2.5e4, 5e4, 7.5e4), labels = c('0', '25K', '50K', '75K'))
ggsave('Popularity by Property - Barplot.png', width = 10, height = 6)
```
```{r}

var_ = listings.df$host_total_listings_count
quartiles = quantile(var_, probs=c(0.25, 0.75))

lower = quartiles[1] - .5 * IQR(var_)
upper = quartiles[2] + .5 * IQR(var_)

subset(listings.df, var_ > lower & var_ < upper) %>%
  ggplot(aes(reorder(state, host_total_listings_count, decreasing = TRUE), 
             host_total_listings_count)) + 
  geom_boxplot(aes(color = airbnb_red), show.legend = FALSE) +
  theme_few() +
  labs(title = 'Property Saturation',
       x = 'State',
       y = 'Hosts - Total Listings') 
    # scale_y_continuous(breaks = c(0, 2.5e6, 5e6, 7.5e6, 1e7), labels = c('0', '2.5M', '5M', '7.5M', '10M'))
  ggsave('Property Saturation - Boxplot.png', width = 10, height = 6)
  
```

```{r}
listings.df %>%
  mutate(neighborhood_overview = gsub(',|br|<|>|/|\\)|\\(|\\.|-', '', 
                                      tolower(neighborhood_overview))) %>%
  tidyr::separate_rows(neighborhood_overview, sep = ' ') %>%
  mutate(neighborhood_overview = gsub('^and$|^&$|^the$|^to$|^is$|^a$|^of$|^in$|^from$|^are$|
                                      ^you$|^with$|^on$|away$|^for$|^this$|^all$|or$|^street$|
                                      ^area$|^close$|^just$|^at$|^minutes$|^there$|^it$|^as$|^also$|
                                      ^one$|^many$|^has$|^that$|^very$|^great$|^distance$|^you$','', 
                                      neighborhood_overview)) %>%
  drop_na() %>%
  group_by(city, neighborhood_overview) %>%
  distinct() %>%
  summarise(count = n()) %>%
  arrange(desc(count))
```

```{r}
top10_neighborhoods = listings.df %>%
  group_by(neighbourhood_cleansed) %>%
  summarise(count = n()) %>%
  arrange(desc(count)) %>%
  filter(!neighbourhood_cleansed %in% c('Unincorporated Areas',
                                      'Primary Urban Center')) %>%
  head(10) %>%
  summarise(neighbourhood_cleansed = neighbourhood_cleansed) %>%
  as_vector()
```


```{r}
listings.df %>%
  filter(neighbourhood_cleansed %in% top10_neighborhoods)
```



```{r}
reviews.df %>%
  na.omit(date) %>%
  summarise(min = min(date),
            max = max(date))
```

```{r}
reviews.df %>%
  ggplot(aes(year)) + 
  geom_bar(aes(fill = airbnb_red), show.legend = FALSE) +
  # geom_density(aes(date, after_stat(count)), show.legend = FALSE) +
  theme_few() +
  scale_x_continuous(breaks = c(2009:2022)) +
  scale_y_continuous(breaks = c(0, 5e5, 1e6, 1.5e6, 2e6),
                     labels = c('0', '500K', '1M', '1.5M', '2M')) +
  labs(title = 'Consumer Travel by Year',
       x = 'Year',
       y = 'Count', 
       color = FALSE)
  ggsave('Travel by Year - Barplot.png', width = 10, height = 6)
```



```{r}
listings.df %>%
  na.omit(host_since) %>%
  mutate(host_since = year(host_since)) %>%
  # group_by(host_since) %>%
  # summarise(count = n()) %>%
  ggplot(aes(host_since, number_of_reviews)) + 
  geom_col(aes(fill = airbnb_red), show.legend = FALSE) +
  # facet_wrap(. ~ room_type, scales = 'free') +
  theme_few() +
  # scale_x_continuous(breaks = c(2010, 2015, 2020)) +
  scale_x_continuous(breaks = c(2008:2022)) +
  scale_y_continuous(breaks = c(5e4, 1e5, 1.5e5, 2e5), 
                     labels = c('50K', '100K', '150K', '200K')) +
  labs(title = 'Competition among AirBNB Hosts',
       x = 'Year',
       y = 'Property Hosts')
  ggsave('Host Competition - Barplot.png', width = 10, height = 6)
  
```

```{r}
# look at compression nights
reviews.df %>%
  group_by(year) %>%
  
```

```{r}
reviews.df
listings.df
```


```{r}
reviews.df %>%
  group_by(year, month) %>%
  summarise(price = mean(price)) %>%
  ggplot(aes(month, price)) + 
  geom_point(aes(color = airbnb_red), show.legend = FALSE) +
  geom_smooth(aes(color = airbnb_green), show.legend = FALSE, se = FALSE) +
  theme_few() +
  facet_grid(. ~ year) +
  scale_y_continuous(breaks = c(50, 150, 250),
                     labels = c('$50', '$150', '$250')) +
  scale_x_continuous(breaks = c(3, 6, 9)) +
  labs(title = 'Average AirBNB costs throughout time',
       x = 'Month',
       y = 'Price')
  ggsave('Cost per time - Scatterplot.png', width = 10, height = 6)
```
```{r}
reviews.df
listings.df
```

```{r}
reviews.df %>%
  group_by(quarter, year) %>%
  summarise(price = mean(price)) %>%
  ggplot(aes(year, price)) +
  geom_point(aes(color = airbnb_red), show.legend = FALSE) +
  facet_grid(. ~ quarter) + 
  theme_few()
  
```


```{r}
gas.df = read_csv('./gas_prices.csv', show_col_types = FALSE)
gas.df = gas.df %>%
  mutate(date = mdy(date),
         month = month(date),
         year = year(date))

gas.df %>%
  group_by(year, month) %>%
  summarise(price = mean(price)) %>%
  ggplot(aes(month, price)) + 
  geom_point(aes(color = airbnb_red), show.legend = FALSE) +
  geom_smooth(aes(color = airbnb_green), show.legend = FALSE, se = FALSE) +
  theme_few() +
  facet_grid(. ~ year) +
  labs(title = 'US Gasoline Costs throughout Time',
       x = 'Month',
       y = 'Price')
  ggsave('Gas Cost per time - Scatterplot.png', width = 10, height = 6)
```

```{r}
reviews.df
  
```

```{r}
reviews.df %>%
  group_by(month) %>%
  summarise(year = year, count = n()) %>%
  ggplot(aes(month, count)) +
  geom_col(aes(fill = airbnb_red), show.legend = FALSE) +
  scale_x_continuous(breaks = c(1:12)) +
  scale_y_continuous(breaks = c(0, 2.5e5, 5e5, 7.5e5, 1e6),
                     labels = c(0, '250K', '500K', '750K', '1M')) +
  theme_few() +
  
  labs(title = 'Varying cost through Seasons',
       x = 'Month',
       y = 'Count')
  ggsave('Seasonal Cost - Scatterplot.png', width = 10, height = 6)
```

```{r}
reviews.df
```


```{r}
reviews.df %>%
  group_by(month, year) %>%
  summarise(count = n()) %>%
  arrange(desc(count), year) %>%
  summarise(first(year, count))
```

```{r}
df = listings.df %>%
  select(id, host_since) %>%
  merge(., reviews.df %>% select(id, year),  by = 'id')
```


```{r}
df %>%
  mutate(host_since = year(host_since)) %>%
  group_by(host_since) %>%
  summarise(count = n())
```

```{r}
combined.df = listings.df %>%
  select(id, accommodates, bathrooms, bedrooms, beds, host_since) %>%
  merge(., reviews.df, by = 'id')
  
```

```{r}
listings.df %>%
  na.omit(host_since) %>%
  mutate(host_since = year(host_since)) %>%
  # group_by(host_since) %>%
  # summarise(count = n()) %>%
  ggplot(aes(host_since, number_of_reviews)) + 
  geom_col(aes(fill = airbnb_red), show.legend = FALSE) +
  # facet_wrap(. ~ room_type, scales = 'free') +
  theme_few() +
  # scale_x_continuous(breaks = c(2010, 2015, 2020)) +
  scale_x_continuous(breaks = c(2008:2022)) +
  scale_y_continuous(breaks = c(5e4, 1e5, 1.5e5, 2e5), 
                     labels = c('50K', '100K', '150K', '200K')) 
  # labs(title = 'Competition among AirBNB Hosts',
  #      x = 'Year',
  #      y = 'Property Hosts')
  # ggsave('Host Competition - Barplot.png', width = 10, height = 6)
  
```

